"""Persistence for Slack bot records (RC-5).

`LedgerListStore`, deliberately — the same store `notifications/store.py` uses for
ActionHub triggers, and for the same reason. A bot record is *delivery configuration
another instance must see*: the supervisor process reads it to decide which sockets to
open, and on serverless a record written by one instance must be visible to the next.
The file-backed store is what once let a brief subscription be "created" into a
read-only bundle and evaporate with the response, so every cron tick evaluated zero
briefs. The Ledger rides `AUGHOR_DB_URL`, which is durable.

It also means **no migration**, which keeps this wave clear of the numbering trap
entirely (`PRAGMA user_version` has to be read off the LIVE db, and no hermetic test
can catch a wrong number).

Secrets are encrypted on the way in and decrypted only for the caller that must open a
socket. Read paths that serve the API use `SlackBot.to_safe_dict`.
"""
from __future__ import annotations

import hmac
import os
import secrets
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Optional

from aughor.db.sqlite_util import resolve_db_path
from aughor.secretvault import decrypt_secret, encrypt_secret
from aughor.slackbots.models import SlackBot, decrypt_secrets, encrypt_secrets
from aughor.util.json_store import LedgerListStore
from aughor.util.time import now_iso_z

_DIR = resolve_db_path("AUGHOR_SLACKBOTS_DIR", Path("data"))
_STORE = LedgerListStore(_DIR / "slack_bots.json")


#: The supervisor's own credential, issued BY the app.
#:
#: `/slack-bots/runtime` is the one route that returns raw tokens, so it must know who
#: is asking. Reusing `AUGHOR_API_KEY` for that — the first version of this gate — made
#: the remedy "export a variable and restart everything", which locks every other client
#: out of the API to protect one route, and cannot be done from inside the product at
#: all. A scoped key can be generated by a button, is read per request (so nothing
#: restarts), and leaves the rest of the deployment exactly as the operator set it.
_KEYS = LedgerListStore(_DIR / "supervisor_key.json")
_KEY_ROW = "supervisor"


def _new_id() -> str:
    return f"sb_{uuid.uuid4().hex[:12]}"


#: AO-2e — how long the PREVIOUS key keeps opening the door after a rotation. Measured
#: 2026-10-03: "Regenerate" replaced the key at once, so a running supervisor lost its
#: registry read on its next reconcile — every bot dark within 30 s, before the operator
#: had even pasted the new line. Ten minutes is a paste and a restart with room to spare;
#: the status route says the deadline so nobody has to guess it.
KEY_GRACE_S = int(os.environ.get("AUGHOR_SUPERVISOR_KEY_GRACE_S", "600"))


def _utcnow() -> datetime:
    """The clock, as a function so a test can move it."""
    return datetime.now(timezone.utc)


def _key_row() -> Optional[dict]:
    return next((r for r in _KEYS.all() if r.get("id") == _KEY_ROW), None)


def _previous_still_valid(row: dict) -> bool:
    until = str(row.get("previous_valid_until") or "")
    if not until or not row.get("previous_key"):
        return False
    try:
        return _utcnow() < datetime.fromisoformat(until)
    except ValueError:
        return False


def issue_supervisor_key() -> str:
    """Mint a supervisor key, store it encrypted, and return it ONCE.

    Issuing replaces: one deployment, one key, and a rotation is the same gesture as a
    first issue — except that the key being replaced stays valid for :data:`KEY_GRACE_S`
    (AO-2e), so the supervisor that holds it keeps its sockets until the new line is in
    place. The plaintext is returned only here — every later read is a comparison, never
    a disclosure, which is `credentials.py`'s rule for anything a reader could use.
    """
    raw = secrets.token_urlsafe(32)
    row = _key_row() or {}
    carried: dict = {}
    if row.get("key"):
        carried = {
            "previous_key": row["key"],
            "previous_valid_until":
                (_utcnow() + timedelta(seconds=KEY_GRACE_S)).isoformat(timespec="seconds"),
        }
    _KEYS.upsert({"id": _KEY_ROW, "key": encrypt_secret(raw), "created_at": now_iso_z(),
                  **carried})
    return raw


def supervisor_key_issued_at() -> str:
    """When the current key was minted, or "" when none exists. Never the key itself."""
    row = _key_row()
    return str(row.get("created_at", "")) if row else ""


def supervisor_key_status() -> dict:
    """Whether a key exists, when it was minted, and until when the previous one still
    opens the door ("" once the grace has passed or none was replaced). Never a key."""
    row = _key_row() or {}
    return {
        "issued": bool(row.get("created_at")),
        "issued_at": str(row.get("created_at", "")),
        "previous_valid_until": (str(row.get("previous_valid_until", ""))
                                 if _previous_still_valid(row) else ""),
        "grace_s": KEY_GRACE_S,
    }


def supervisor_key_matches(candidate: str) -> bool:
    """Constant-time comparison against the stored key — or, inside the grace window,
    against the one it replaced. False when none is issued."""
    row = _key_row()
    if not row or not candidate:
        return False
    stored = decrypt_secret(str(row.get("key", "")) or "") or ""
    if stored and hmac.compare_digest(stored, candidate):
        return True
    if _previous_still_valid(row):
        previous = decrypt_secret(str(row.get("previous_key", "")) or "") or ""
        return bool(previous) and hmac.compare_digest(previous, candidate)
    return False


# ── Liveness (AO-2a): what the supervisor said it has open, and when ──────────────
#
# A third store, not a field on the bot: a heartbeat every 30 s that re-saved every
# encrypted bot row would churn the credential file to say "still here". One row per
# supervisor process, so two supervisors on one API are told apart and neither erases
# the other's bots.
_RUNTIME = LedgerListStore(_DIR / "supervisor_runtime.json")

#: A beat older than this many reconcile intervals means the process is gone, whatever
#: its last beat said.
HEARTBEAT_STALE_INTERVALS = 3

#: The one command, said wherever "not listening" is said.
SUPERVISOR_START_HINT = "start the supervisor: cd bots/slack && npm run dev"


def record_heartbeat(supervisor_id: str, running: list[str], failed: list[dict],
                     reconcile_ms: int) -> dict:
    """Store what one supervisor has open right now. ``since`` survives across beats of
    an unbroken run and restarts after a silence longer than the stale window."""
    now = _utcnow()
    now_iso = now.isoformat(timespec="seconds")
    prev = next((r for r in _RUNTIME.all() if r.get("id") == supervisor_id), None)
    since = now_iso
    if prev and _fresh(prev, now):
        since = str(prev.get("since") or now_iso)
    row = {
        "id": supervisor_id, "since": since, "last_seen_at": now_iso,
        "running": [str(b) for b in running],
        "failed": [{"id": str(f.get("id", "")), "error": str(f.get("error", ""))[:300]}
                   for f in failed if isinstance(f, dict)],
        "reconcile_ms": max(1000, int(reconcile_ms or 30000)),
    }
    _RUNTIME.upsert(row)
    return row


def _fresh(row: dict, now: Optional[datetime] = None) -> bool:
    now = now or _utcnow()
    try:
        seen = datetime.fromisoformat(str(row.get("last_seen_at") or ""))
    except ValueError:
        return False
    stale_after = timedelta(milliseconds=int(row.get("reconcile_ms") or 30000)
                            * HEARTBEAT_STALE_INTERVALS)
    return now - seen < stale_after


def liveness_fields(bot_id: str) -> dict:
    """``listening`` (the fresh beat that has this bot open) and ``liveness_hint`` (why
    not, with the command) — what the bot card and the agent's Map read."""
    now = _utcnow()
    rows = sorted(_RUNTIME.all(), key=lambda r: str(r.get("last_seen_at") or ""), reverse=True)
    for r in rows:
        if _fresh(r, now) and bot_id in (r.get("running") or []):
            return {"listening": {"supervisor_id": r["id"], "since": r.get("since", ""),
                                  "last_seen_at": r.get("last_seen_at", "")},
                    "liveness_hint": ""}
    for r in rows:
        if not _fresh(r, now):
            continue
        hit = next((f for f in (r.get("failed") or []) if f.get("id") == bot_id), None)
        if hit:
            return {"listening": None,
                    "liveness_hint": f"not listening — the supervisor could not start it: "
                                     f"{hit.get('error') or 'unknown error'}"}
    for r in rows:
        if bot_id in (r.get("running") or []):
            return {"listening": None,
                    "liveness_hint": f"not listening — last heard "
                                     f"{r.get('last_seen_at', '')}; {SUPERVISOR_START_HINT}"}
    return {"listening": None,
            "liveness_hint": f"not listening — no supervisor has reported; {SUPERVISOR_START_HINT}"}


def list_bots(*, include_disabled: bool = True) -> list[SlackBot]:
    """Every stored bot, secrets still encrypted."""
    out = [SlackBot(**d) for d in _STORE.all()]
    return out if include_disabled else [b for b in out if b.enabled]


def get_bot(bot_id: str) -> Optional[SlackBot]:
    d = _STORE.get(bot_id)
    return SlackBot(**d) if d else None


def get_bot_decrypted(bot_id: str) -> Optional[SlackBot]:
    """The form the supervisor needs — plaintext tokens, for opening a socket."""
    bot = get_bot(bot_id)
    return decrypt_secrets(bot) if bot else None


def save_bot(bot: SlackBot) -> SlackBot:
    """Create or update. Secrets are encrypted here so no caller can forget to."""
    if not bot.id:
        bot = bot.model_copy(update={"id": _new_id()})
    bot = bot.model_copy(update={"updated_at": now_iso_z()})
    _STORE.upsert(encrypt_secrets(bot).to_dict())
    return bot


def delete_bot(bot_id: str) -> bool:
    return _STORE.delete(bot_id)


def bots_for_owner(owner: str) -> list[SlackBot]:
    """Every bot belonging to one person, plus the org's unowned ones.

    Unowned bots are included deliberately: `owner=""` is what every bot created before
    VA-9b carries, and a shared workspace bot is a legitimate thing to keep. Excluding
    them would make this field a silent migration rather than an addition.
    """
    return [b for b in list_bots() if not b.owner or b.owner == owner]


def bots_for_agent(agent_id: str) -> list[SlackBot]:
    """Every bot fronting one agent — the query an agent-delete cascade needs, so a
    deleted agent does not leave a live socket answering as it."""
    return [b for b in list_bots() if b.agent_id == agent_id]
